name: Update Listen on Repeat Widget

on:
  workflow_dispatch:
  schedule:
    - cron: "17 */3 * * *"

jobs:
  update-widget:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Update Discord widget
        run: node src/update-widget.js
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          SPOTIFY_TIME_RANGE: short_term
          SPOTIFY_LIMIT: "5"

          DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
          DISCORD_IDENTITY_ID: "0"
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
